Executable Jar runtime error prevents starting.
Executable Jar was throwing the follwing error:
Error: Could not find or load main class com.beowurks.jequity.main.Main
Caused by: java.lang.ClassNotFoundException: com.beowurks.jequity.main.Main

Turns out the signed Bouncy Castle library caused the problem. So I removed it as JEquity is not outputting a signed PDF.