Found another signed jar in JasperReports.
Which caused the following:
Error: Could not find or load main class com.beowurks.jequity.main.Main
Caused by: java.lang.ClassNotFoundException: com.beowurks.jequity.main.